# --- Deployment definition ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptorec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptorec
  template:
    metadata:
      labels:
        app: cryptorec
    spec:
      containers:
        - name: cryptorec
          image: valentinnidelciu/cryptorec:0.0.5
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always

---

# --- Service definition ---
apiVersion: v1
kind: Service
metadata:
  name: cryptorec
spec:
  selector:
    app: cryptorec
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer